#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<EOSQL
CREATE USER ${AIRFLOW_DB_USER} WITH PASSWORD '${AIRFLOW_DB_PASSWORD}';
CREATE DATABASE ${AIRFLOW_DB} OWNER ${AIRFLOW_DB_USER};
CREATE USER ${SUPERSET_DB_USER} WITH PASSWORD '${SUPERSET_DB_PASSWORD}';
CREATE DATABASE ${SUPERSET_DB} OWNER ${SUPERSET_DB_USER};
EOSQL